---
- name: Create a '~/.config/ccache/ccache.conf' file
  ansible.builtin.copy:
    src: ccache.conf
    dest: $HOME/.config/ccache/ccache.conf
    force: false
    mode: '0755'
  become: false

- name: Create a directory for a '~/.R/Makevars' file if it does not exist
  ansible.builtin.file:
    path: $HOME/.R
    state: directory
    mode: '0755'
  become: false

- name: Create a '~/.R/Makevars' file
  ansible.builtin.copy:
    src: Makevars
    dest: $HOME/.R/Makevars
    force: false
    mode: '0755'
  become: false

- name: Create a '~/.Renviron' file
  ansible.builtin.copy:
    src: .Renviron
    dest: $HOME/.Renviron
    force: false
    mode: '0755'
  become: false

- name: Create a '~/.Rprofile' file
  ansible.builtin.copy:
    src: .Rprofile
    dest: $HOME/.Rprofile
    force: false
    mode: '0755'
  become: false

- name: Create a directory for R packages if it does not exist
  ansible.builtin.file:
    path: $HOME/R/library
    state: directory
    mode: '0755'
  become: false

- name: Ensure various software packages are installed
  ansible.builtin.dnf:
    name:
      - ccache
      - devscripts-checkbashisms
      - gdal-devel
      - geos-devel
      - gsl-devel
      - libjpeg-turbo-devel
      - poppler-cpp-devel
      - proj-devel
      - R
    state: present
  become: true

- name: Install some R packages
  ansible.builtin.command: >-
      Rscript --no-restore --no-save -e "
        pkgs <- c(
            'bookdown',
            'data.table',
            'getPass',
            'knitr',
            'pkgbuild',
            'raster',
            'rgl',
            'rmarkdown',
            'roxygen2',
            'pdftools',
            'SimInf',
            'sp',
            'stringi',
            'xml2')
        pkgs <- pkgs[!(pkgs %in% installed.packages()[,'Package'])]
        if (length(pkgs)) {
            install.packages(pkgs, Ncpus = parallel::detectCores())
            cat('changed')
        }"
  register: result
  changed_when: "'changed' in result.stdout"
  become: false
