---
- name: Create a directory for a '~/.R/Makevars' file if it does not exist
  ansible.builtin.file:
    path: $HOME/.R
    state: directory
    mode: '0755'
  become: false

- name: Create a '~/.R/Makevars' file
  ansible.builtin.copy:
    src: Makevars
    dest: $HOME/.R/Makevars
    force: false
    mode: '0755'
  become: false

- name: Create a '~/.Renviron' file
  ansible.builtin.copy:
    src: .Renviron
    dest: $HOME/.Renviron
    force: false
    mode: '0755'
  become: false

- name: Create a '~/.Rprofile' file
  ansible.builtin.copy:
    src: .Rprofile
    dest: $HOME/.Rprofile
    force: false
    mode: '0755'
  become: false

- name: Create a directory for R packages if it does not exist
  ansible.builtin.file:
    path: $HOME/R/library
    state: directory
    mode: '0755'
  become: false

- name: Ensure various software packages are installed
  ansible.builtin.dnf:
    name:
      - gdal-devel
      - geos-devel
      - gsl-devel
      - libjpeg-turbo-devel
      - poppler-cpp-devel
      - proj-devel
      - R
    state: present
  become: true

- name: Install some R packages
  become: false
  ansible.builtin.command: >-
      Rscript --no-restore --no-save -e "
        if (!('{{ item }}' %in% installed.packages()[,'Package'])) {
            tryCatch(install.packages('{{ item }}'),
                     warning = function(w) stop(w))
            cat('Install package')
        }"
  register: r_install
  changed_when: "'Install package' in r_install.stdout"
  with_items:
    - bookdown
    - data.table
    - getPass
    - knitr
    - raster
    - rgl
    - rmarkdown
    - roxygen2
    - pdftools
    - SimInf
    - sp
    - stringi
    - xml2
