---
- name: Configure my Fedora workstation
  hosts: workstation
  become: yes
  tasks:

  - name: Ensure required software packages to run this playbook are installed
    dnf:
      name:
        - pcsc-lite
        - pcsc-tools
        - python3-psutil
        - restic

  - name: Start and enable pcscd.service
    systemd:
      name: pcscd.service
      state: started
      enabled: yes

  - name: Start and enable pcscd.socket
    systemd:
      name: pcscd.socket
      state: started
      enabled: yes

  - name: Setup gpg key management
    become: false
    command: >-
      bash -c "
        if test ! -d ${HOME}/.gnupg; then
          mkdir $HOME/.gnupg
          echo 'personal-cipher-preferences AES256 AES192 AES' > $HOME/.gnupg/gpg.conf
          echo 'personal-digest-preferences SHA512 SHA384 SHA256' >> $HOME/.gnupg/gpg.conf
          echo 'personal-compress-preferences ZLIB BZIP2 ZIP Uncompressed' >> $HOME/.gnupg/gpg.conf
          echo 'default-preference-list SHA512 SHA384 SHA256 AES256 AES192 AES ZLIB BZIP2 ZIP Uncompressed' >> $HOME/.gnupg/gpg.conf
          echo 'cert-digest-algo SHA512' >> $HOME/.gnupg/gpg.conf
          echo 's2k-digest-algo SHA512' >> $HOME/.gnupg/gpg.conf
          echo 's2k-cipher-algo AES256' >> $HOME/.gnupg/gpg.conf
          echo 'charset utf-8' >> $HOME/.gnupg/gpg.conf
          echo 'fixed-list-mode' >> $HOME/.gnupg/gpg.conf
          echo 'no-comments' >> $HOME/.gnupg/gpg.conf
          echo 'no-emit-version' >> $HOME/.gnupg/gpg.conf
          echo 'no-greeting' >> $HOME/.gnupg/gpg.conf
          echo 'keyid-format 0xlong' >> $HOME/.gnupg/gpg.conf
          echo 'list-options show-uid-validity' >> $HOME/.gnupg/gpg.conf
          echo 'verify-options show-uid-validity' >> $HOME/.gnupg/gpg.conf
          echo 'with-fingerprint' >> $HOME/.gnupg/gpg.conf
          echo 'require-cross-certification' >> $HOME/.gnupg/gpg.conf
          echo 'no-symkey-cache' >> $HOME/.gnupg/gpg.conf
          echo 'use-agent' >> $HOME/.gnupg/gpg.conf
          echo 'throw-keyids' >> $HOME/.gnupg/gpg.conf
          echo 'keyserver hkps://keys.openpgp.org' >> $HOME/.gnupg/gpg.conf
          chmod 700 $HOME/.gnupg
          chmod 600 $HOME/.gnupg/gpg.conf
          gpg --auto-key-locate keyserver --locate-keys stefan.widgren@gmail.com
          KEYID=$(gpg --list-keys --with-colons stefan.widgren@gmail.com | awk -F: '/fpr:/ {print $10}' | head -n 1)
          echo -e '5\ny\n' | gpg --command-fd 0 --edit-key $KEYID trust
          echo 'Setup gpg'
        fi"
    register: setup_gpg
    changed_when: "'Setup gpg' in setup_gpg.stdout"

  - name: Create a configuration file for gpg-agent
    become: false
    copy:
      dest: $HOME/.gnupg/gpg-agent.conf
      force: no
      content: |
        enable-ssh-support

  - name: Ensure the 'SSH_AUTH_SOCK' is set
    become: false
    lineinfile:
      path: $HOME/.bashrc
      regexp: '^export SSH_AUTH_SOCK='
      line: export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

  - name: Ensure the 'gpg-agent' is launched
    become: false
    lineinfile:
      path: $HOME/.bashrc
      regexp: '^gpgconf --launch gpg-agent'
      line: gpgconf --launch gpg-agent

  - name: Restore backup
    become: false
    command: >-
      bash -c "
        if test ! -d ${HOME}/$(pass restic/backup | sed -n 3p); then
          restic --password-file <(pass restic | sed -n 1p) -r $(pass restic/backup | sed -n 1p) restore latest --target $HOME
          echo 'Restore backup'
        fi"
    register: restore_backup
    changed_when: "'Restore backup' in restore_backup.stdout"

  - name: Ensure the latest version of various software packages are installed
    dnf:
      name:
        - cppcheck
        - devscripts-checkbashisms
        - emacs
        - gdal-devel
        - gdb
        - geos-devel
        - gsl-devel
        - pandoc
        - pandoc-citeproc
        - proj-devel
        - R
        - sqlite-devel
        - texlive-adjustbox
        - texlive-algorithmicx
        - texlive-authoraftertitle
        - texlive-datetime
        - texlive-draftwatermark
        - texlive-doublestroke
        - texlive-floatrow
        - texlive-framed
        - texlive-lastpage
        - texlive-lato
        - texlive-lettrine
        - texlive-mdframed
        - texlive-multirow
        - texlive-numprint
        - texlive-preprint
        - texlive-sidecap
        - texlive-sttools
        - texlive-tcolorbox
        - texlive-titling
        - texlive-threeparttable
        - texlive-totcount
        - texlive-was
        - texlive-xpatch
        - udunits2-devel
      state: latest

  - name: Turn off the Gnome beep sound
    become: false
    dconf:
      key: "/org/gnome/desktop/sound/event-sounds"
      value: "false"
      state: present

  - name: Set wallpaper
    become: false
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'{{ lookup('env', 'PWD') }}/wallpaper.jpg'"
      state: present

  - name: Ensure the 'alias backup' is set
    become: false
    lineinfile:
      path: $HOME/.bashrc
      regexp: '^alias backup='
      line: alias backup="restic --password-file <(pass restic | sed -n 1p) -r \$(pass restic/backup | sed -n 1p) backup \$(pass restic/backup | sed -n 2p)"

  - name: Ensure the 'alias backup_setup' is set
    become: false
    lineinfile:
      path: $HOME/.bashrc
      regexp: '^alias backup_setup='
      line: alias backup_setup="restic --password-file <(pass restic | sed -n 1p) -r \$(pass restic/backup_setup | sed -n 1p) backup \$(pass restic/backup_setup | sed -n 2p)"

  - name: Create a directory for R packages if it does not exist
    become: false
    file:
      path: $HOME/R/library
      state: directory
      mode: '0755'

  - name: Create a directory for a '~/.R/Makevars' file if it does not exist
    become: false
    file:
      path: $HOME/.R
      state: directory
      mode: '0755'

  - name: >
      Create a '~/.R/Makevars' file with some out-commented
      examples of how to modify package compilation.
    become: false
    copy:
      dest: $HOME/.R/Makevars
      force: no
      content: |
        # CFLAGS = -Wall -pedantic
        # CFLAGS = -Wall -Wextra -pedantic -Wno-cast-function-type
        # CFLAGS = -Wall -Wextra -pedantic
        # CFLAGS = -Wall -flto -pedantic
        # CFLAGS = -Wall -Wextra -pedantic -ggdb -O0
        # CFLAGS = -ggdb -O0
        # CFLAGS=-g -O3 -Wall -pedantic -std=gnu99 -mtune=native -pipe
        # CFLAGS=
        # CC=clang
        # CC=ccache gcc
        # VER=
        # CCACHE=ccache
        # CC=$(CCACHE) gcc$(VER)
        # CXX=$(CCACHE) g++$(VER)
        # CXX11=$(CCACHE) g++$(VER)
        # CXX14=$(CCACHE) g++$(VER)
        # FC=$(CCACHE) gfortran$(VER)
        # F77=$(CCACHE) gfortran$(VER)

  - name: Create a '~/.Renviron' file
    become: false
    copy:
      dest: $HOME/.Renviron
      force: no
      content: |
        R_LIBS_USER=~/R/library

  - name: Create a '~/.Rprofile' file
    become: false
    copy:
      dest: $HOME/.Rprofile
      force: no
      content: |
        options(repos = c(CRAN="https://cran.r-project.org"))

  - name: Create a '~/.gdbinit' file
    become: false
    copy:
      dest: $HOME/.gdbinit
      force: no
      content: |
        set style enabled off
        set history save on

  - name: Ensure that the 'emacs' configuration exists
    become: false
    git:
      repo: 'https://github.com/stewid/.emacs.d.git'
      dest: $HOME/.emacs.d
      update: no

  - name: Ensure the EDITOR environment variable is set
    become: false
    lineinfile:
      path: $HOME/.bashrc
      regexp: '^export EDITOR='
      line: export EDITOR=emacs

  - name: Install some R packages
    become: false
    command: >-
        Rscript --no-restore --no-save -e "
          if (!('{{ item }}' %in% installed.packages()[,'Package'])) {
              tryCatch(install.packages('{{ item }}'),
                       warning = function(w) stop(w))
              cat('Install package')
          }"
    register: r_install
    changed_when: "'Install package' in r_install.stdout"
    with_items:
      - bookdown
      - getPass
      - knitr
      - raster
      - rgl
      - rmarkdown
      - roxygen2
      - pdftools
      - SimInf
      - sf
      - sp
      - xml2
