---
- name: Configure my Fedora workstation
  hosts: workstation
  roles:
    - bashrc
    - dnf
    - git
    - gnome
    - R
  become: yes
  tasks:

  - name: Ensure required software packages to run this playbook are installed
    dnf:
      name:
        - pass
        - restic

  - name: Set hostname to the model name
    ansible.builtin.command: >-
        bash -c "
          MODELNAME=$(dmidecode -s system-version | sed 's/[[:space:]]//g')
          if test \"$(hostname)\" != \"$MODELNAME\"; then
            hostnamectl set-hostname --static --pretty $MODELNAME
            echo 'Set hostname'
          fi"
    register: set_hostname
    changed_when: "'Set hostname' in set_hostname.stdout"

  - name: Restore backup
    become: false
    ansible.builtin.command: >-
      bash -c "
        if test ! -d ${HOME}/$(pass restic | sed -n 4p); then
          restic --password-file <(pass restic | sed -n 1p) -r $(pass restic | sed -n 2p) restore latest --target $HOME
          echo 'Restore backup'
        fi"
    register: restore_backup
    changed_when: "'Restore backup' in restore_backup.stdout"

  - name: Ensure the latest version of various software packages are installed
    dnf:
      name:
        - cppcheck
        - devscripts-checkbashisms
        - emacs
        - gdal-devel
        - gdb
        - geos-devel
        - gsl-devel
        - mesa-libGLU-devel
        - libcurl-devel
        - libjpeg-turbo-devel
        - libxml2-devel
        - openssl-devel
        - pandoc
        - pdf2svg
        - poppler-cpp-devel
        - poppler-glib-devel
        - proj-devel
        - R
        - sqlite-devel
        - texlive-adjustbox
        - texlive-algorithmicx
        - texlive-authoraftertitle
        - texlive-datetime
        - texlive-draftwatermark
        - texlive-doublestroke
        - texlive-floatrow
        - texlive-framed
        - texlive-lastpage
        - texlive-lato
        - texlive-lettrine
        - texlive-mdframed
        - texlive-multirow
        - texlive-numprint
        - texlive-pdfcrop
        - texlive-preprint
        - texlive-sidecap
        - texlive-standalone
        - texlive-sttools
        - texlive-tcolorbox
        - texlive-titling
        - texlive-threeparttable
        - texlive-totcount
        - texlive-was
        - texlive-xpatch
        - udunits2-devel
      state: latest

  - name: Create a directory for mounting restic backup files
    become: false
    file:
      path: $HOME/restic
      state: directory
      mode: '0755'

  - name: Create a '~/.gdbinit' file
    ansible.builtin.copy:
      src: .gdbinit
      dest: $HOME/.gdbinit
      force: false
    become: false

  - name: Ensure that the 'emacs' configuration exists
    ansible.builtin.git:
      repo: 'https://github.com/stewid/.emacs.d.git'
      dest: $HOME/.emacs.d
      update: false
    become: false
