---
- name: Turn off the Gnome beep sound
  command: >-
    bash -c "
      if [[ $(dconf read /org/gnome/desktop/sound/event-sounds) != \"false\" ]]; then
        dconf write /org/gnome/desktop/sound/event-sounds false
        echo "changed"
      fi"
  register: result
  changed_when: "'changed' in result.stdout"
  become: false

- name: Set wallpaper
  command: >-
    bash -c "
      if [[ -z $(dconf read /org/gnome/desktop/background/picture-uri) ]]; then
        dconf write /org/gnome/desktop/background/picture-uri \"'file://$PWD/roles/gnome/files/wallpaper.jpg'\"
        echo "changed"
      fi"
  register: result
  changed_when: "'changed' in result.stdout"
  become: false

- name: Specify the list view in nautilus
  command: >-
    bash -c "
      if [[ $(dconf read /org/gnome/nautilus/preferences/default-folder-viewer) != \"'list-view'\" ]]; then
        dconf write /org/gnome/nautilus/preferences/default-folder-viewer \"'list-view'\"
        echo "changed"
      fi"
  register: result
  changed_when: "'changed' in result.stdout"
  become: false

- name: Specify the default zoom level in nautilus
  command: >-
    bash -c "
      if [[ $(dconf read /org/gnome/nautilus/list-view/default-zoom-level) != \"'small'\" ]]; then
        dconf write /org/gnome/nautilus/list-view/default-zoom-level \"'small'\"
        echo "changed"
      fi"
  register: result
  changed_when: "'changed' in result.stdout"
  become: false

- name: Show hidden files in nautilus
  command: >-
    bash -c "
      if [[ $(dconf read /org/gtk/gtk4/settings/file-chooser/show-hidden) != \"true\" ]]; then
        dconf write /org/gtk/gtk4/settings/file-chooser/show-hidden true
        echo "changed"
      fi"
  register: result
  changed_when: "'changed' in result.stdout"
  become: false
